import { z } from "zod";
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { ToolContext } from "../server/tools/context.js";
import {
  inspectCompanionSetup,
  previewCompanionSetup,
  applyCompanionSetup,
  validateCompanionSetup,
  CompanionSetupInspection,
  CompanionSetupPreview,
  CompanionSetupApplyResult,
  CompanionSetupValidationResult,
} from "./lifecycle.js";

// ============================================================================
// Schemas for Companion Setup Tools
// ============================================================================

export const InspectCompanionSetupInputSchema = {
  workspace: z
    .string()
    .optional()
    .describe("Workspace directory path (defaults to current working directory)"),
  host_id: z
    .string()
    .optional()
    .describe("Host identifier (optional, auto-detected from workspace if omitted)"),
  scope: z
    .enum(["project", "global"])
    .optional()
    .describe("Configuration scope ('project' or 'global', defaults to 'project')"),
};

export const PreviewCompanionSetupInputSchema = {
  workspace: z
    .string()
    .optional()
    .describe("Workspace directory path (defaults to current working directory)"),
  host_id: z
    .string()
    .optional()
    .describe("Host identifier (optional, auto-detected from workspace if omitted)"),
  scope: z
    .enum(["project", "global"])
    .optional()
    .describe("Configuration scope ('project' or 'global', defaults to 'project')"),
};

export const ApplyCompanionSetupInputSchema = {
  preview_hash: z
    .string()
    .min(1)
    .describe("SHA-256 preview hash generated by preview_companion_setup"),
  preview_id: z
    .string()
    .optional()
    .describe("Preview identifier"),
  baseline_hash: z
    .string()
    .nullable()
    .optional()
    .describe("Expected baseline hash before applying mutation"),
  explicit_approval: z
    .boolean()
    .describe("Explicit user approval confirming mutation authorization"),
  workspace: z
    .string()
    .optional()
    .describe("Workspace directory path (defaults to current working directory)"),
  host_id: z
    .string()
    .optional()
    .describe("Host identifier"),
  scope: z
    .enum(["project", "global"])
    .optional()
    .describe("Configuration scope ('project' or 'global')"),
};

export const ValidateCompanionSetupInputSchema = {
  workspace: z
    .string()
    .optional()
    .describe("Workspace directory path (defaults to current working directory)"),
  host_id: z
    .string()
    .optional()
    .describe("Host identifier (optional, auto-detected if omitted)"),
  scope: z
    .enum(["project", "global"])
    .optional()
    .describe("Configuration scope ('project' or 'global')"),
};

// ============================================================================
// Tool Handlers
// ============================================================================

export async function handleInspectCompanionSetup(
  params: { workspace?: string; host_id?: string; scope?: "project" | "global" },
  context: ToolContext
): Promise<CompanionSetupInspection> {
  return inspectCompanionSetup({
    workspace: params.workspace,
    host_id: params.host_id,
    scope: params.scope,
    registry: context.adapterRegistry,
  });
}

export async function handlePreviewCompanionSetup(
  params: { workspace?: string; host_id?: string; scope?: "project" | "global" },
  context: ToolContext
): Promise<CompanionSetupPreview> {
  return previewCompanionSetup({
    workspace: params.workspace,
    host_id: params.host_id,
    scope: params.scope,
    registry: context.adapterRegistry,
  });
}

export async function handleApplyCompanionSetup(
  params: {
    preview_hash: string;
    preview_id?: string;
    baseline_hash?: string | null;
    explicit_approval: boolean;
    workspace?: string;
    host_id?: string;
    scope?: "project" | "global";
  },
  context: ToolContext
): Promise<CompanionSetupApplyResult> {
  return applyCompanionSetup({
    preview_hash: params.preview_hash,
    preview_id: params.preview_id,
    baseline_hash: params.baseline_hash,
    explicit_approval: params.explicit_approval,
    workspace: params.workspace,
    host_id: params.host_id,
    scope: params.scope,
    registry: context.adapterRegistry,
  });
}

export async function handleValidateCompanionSetup(
  params: { workspace?: string; host_id?: string; scope?: "project" | "global" },
  context: ToolContext
): Promise<CompanionSetupValidationResult> {
  return validateCompanionSetup({
    workspace: params.workspace,
    host_id: params.host_id,
    scope: params.scope,
    registry: context.adapterRegistry,
  });
}

/**
 * Registers companion setup MCP tools on a given McpServer instance.
 */
export function registerCompanionSetupTools(server: McpServer, context: ToolContext): void {
  server.registerTool(
    "inspect_companion_setup",
    {
      description: "Inspect Agent Config Companion MCP registration status for current or specified host harness.",
      inputSchema: InspectCompanionSetupInputSchema,
    },
    async (params) => {
      try {
        const result = await handleInspectCompanionSetup(params, context);
        return { content: [{ type: "text", text: JSON.stringify(result, null, 2) }] };
      } catch (err: any) {
        return { isError: true, content: [{ type: "text", text: `inspect_companion_setup error: ${err.message}` }] };
      }
    }
  );

  server.registerTool(
    "preview_companion_setup",
    {
      description: "Preview exact registration mutation diff, baseline hash, and ownership before modifying host configuration.",
      inputSchema: PreviewCompanionSetupInputSchema,
    },
    async (params) => {
      try {
        const result = await handlePreviewCompanionSetup(params, context);
        return { content: [{ type: "text", text: JSON.stringify(result, null, 2) }] };
      } catch (err: any) {
        return { isError: true, content: [{ type: "text", text: `preview_companion_setup error: ${err.message}` }] };
      }
    }
  );

  server.registerTool(
    "apply_companion_setup",
    {
      description: "Apply companion registration mutation atomically after explicit user approval.",
      inputSchema: ApplyCompanionSetupInputSchema,
    },
    async (params) => {
      try {
        const result = await handleApplyCompanionSetup(params, context);
        return { content: [{ type: "text", text: JSON.stringify(result, null, 2) }] };
      } catch (err: any) {
        return { isError: true, content: [{ type: "text", text: `apply_companion_setup error: ${err.message}` }] };
      }
    }
  );

  server.registerTool(
    "validate_companion_setup",
    {
      description: "Read back effective host state and verify companion MCP reachability and semantic configuration.",
      inputSchema: ValidateCompanionSetupInputSchema,
    },
    async (params) => {
      try {
        const result = await handleValidateCompanionSetup(params, context);
        return { content: [{ type: "text", text: JSON.stringify(result, null, 2) }] };
      } catch (err: any) {
        return { isError: true, content: [{ type: "text", text: `validate_companion_setup error: ${err.message}` }] };
      }
    }
  );
}
